### PR TITLE
Add `encType` argument to the PHP `http_build_query` function

### PR DESCRIPTION
**Pull request by willrowe**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description
- This is a retry of https://github.com/kvz/locutus/pull/217 which was never merged due to testing issues at the time.
- Depending on the encoding type used, it will use either `urlencode` or `rawurlencode`.

### CODE REVIEW

**Comment by kvz** [comment]
Thanks!

**Comment by willrowe** [comment]
Hey @kvz just checking to see when you're planning on releasing a the next version. I'll be needing to use the argument added by this PR soon in another library I help out with.

**Comment by kvz** [comment]
Hi, sure! Just published `+ locutus@2.0.10` 👌

**Comment by willrowe** [comment]
Thanks so much!

**Pull request merged**
