### PR TITLE
Because GLOBAL is deprecated in node

### PR DESCRIPTION
**Pull request by DracoBlue**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description

``` 
"(node:1) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'"
```

### CODE REVIEW

**Comment by kvz** [comment]
Thanks for you PR! It seems this happened going from Node 5->6: https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6

A few things:

- Locutus targets node v4 currently 
- it seems v4 already supports lowercase `global`, so we _might_ be able to support v4-6 by using it
- if we're switching to lowercase `global`, it would need to be implemented across the board, and not just in src/php/var/unserialize.js
- would you expand your PR to do this in all cases? If so, I'm happy to merge. Otherwise I'll have a look soonish myself!

**Comment by DracoBlue** [comment]
I will try a quick sed replace on the cli and update the PR asap

Am 09.08.2016 9:54 vorm. schrieb "Kevin van Zonneveld" <
notifications@github.com>:
>
> Thanks for you PR! It seems this happened going from Node 5->6:
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6
>
> A few things:
>
> Locutus targets node v4 currently
> it seems v4 already supports lowercase global, so we might be able to
support v4-6 by using it
> if we're switching to lowercase global, it would need to be implemented
across the board, and not just in src/php/var/unserialize.js
> would you expand your PR to do this in all cases? If so, I'm happy to
merge. Otherwise I'll have a look soonish myself!

**Comment by DracoBlue** [comment]
@kvz I updated the PR to replace GLOBAL to global in all files (except website - is this necessary?)

**Comment by kvz** [comment]
Hi @DracoBlue, thanks a lot, this is looking good!

**Pull request merged**
