### PR TITLE
std::frexp

### PR DESCRIPTION
**Pull request by oskarlh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description
A JavaScript version of frexp from C or std::frexp from C++.
See http://en.cppreference.com/w/c/numeric/math/frexp
Instead of
`double frexp( double arg, int* exp );`
this is built as
`[double, int] frexp( double arg );`
due to the lack of pointers in JavaScript.
See code comments for further information.

### CODE REVIEW

**Comment by kvz** [comment]
Hey thanks for contributing this! Could you add a test to the header comments of the function similar to how we test other functions? Then we can keep making sure this works well 👌

**Comment by oskarlh** [comment]
Do you mean comments of this kind:
//   example 1: atan(8723321.4)
//   returns 1: 1.5707962121596615
?

**Comment by oskarlh** [comment]
@kvz: done

**Comment by kvz** [comment]
Awesome stuff! 👌

**Comment by oskarlh** [comment]
Thanks!
Guess you'll need to change the "Ehm.. Only 1 C function in all of Locutus?" text 😄

**Comment by kvz** [comment]
I believe/hope this is automated so that should be changed as soon as the site is deployed by travis 👯 but yes, good catch! 😄

**Pull request merged**
