### PR TITLE
Fixed comparison of identical strings

### PR DESCRIPTION
**Pull request by mjomble**
This function returned -1 when comparing identical strings. Now it returns 0.

### CODE REVIEW

**Comment by mjomble** [comment]
Hi, I noticed this was still not merged looks like you missed my second commit :)

**Comment by kvz** [comment]
Hey @mjomble, thank you so much for this PR. I am very sorry for the long wait after you put in this work. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). Unfortunately for your PR this also means it's currently outdated and cannot be merged as is.

I'll close this issues, but if this PR is still relevant to you, please re-open. You should then rebase with this project's `master` branch, make sure it complies with the contributing document (https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md), and then we can merge this in, because the work really does look good to me.

Again, I'm very sorry for not having attended to this earlier, and putting you through all this extra hassle. I hope you'll agree that the project was in a dead-end street though, and with this new big push, we're going somewhere again.

**Comment by mjomble** [comment]
No problem, will take a look at this in the near future.

**Comment by kvz** [comment]
Thanks a lot Andres!

**Pull request closed without merging**
