### PR TITLE
Fix unserialize objects issue

### PR DESCRIPTION
**Pull request by JefferyHus**
When an 'o' is found in the string it is considered an object, in PHP objects are not same as Arrays which is the complete opposite in JavaScript, because an array is at the same time an array.

### CODE REVIEW

**Comment by kvz** [comment]
Can you please make the linting pass and head a function header comment with a test that failed before, passing after your patch?

**Comment by kukawski** [comment]
Thanks for the patch. I have one comment, though:

I believe the 'o' was unhandled on purpose. The 'o' type is quite complex on PHP's side, because it contains the class name of the object that was serialized. The class name can also be namespaced, etc.
Deserializing it to a plain JS object is just a simplification and can't be treated as full PHP port.

We had more tickets regarding the unhandled 'o' type, so maybe it's a good idea to merge this patch, but add a comment in the source code that this is just a simplification and it deserializes to plain JS objects.

**Comment by JefferyHus** [comment]
been a while, is there something that I can do before you merge this patch?

**Comment by kvz** [comment]
If we can have the header test case and the comment about o, I’d be happy to merge

**Comment by kvz** [comment]
Closing due to inactivity

**Pull request closed without merging**
