### PR TITLE
use 1 for loop instead of 4

### PR DESCRIPTION
**Pull request by AyrA**
the 4 loops with these counters (0-19,20-39,40-59,60-79) can be written as one for loop with a switch statement.

### CODE REVIEW

**Comment by kvz** [comment]
Thanks, while to code looks better, have you benchmarked this? Doing more conditions inside a loop can often slow things down. We'd need to doublecheck

**Comment by Theriault** [comment]
If the whole point of this is to get rid of the redundant code, perhaps keeping 4 loops and doing the below would be better on performance/size.

f6c406fdd662608da5aa4ded0de74e2c407045a6

**Comment by rafaelmaza** [comment]
Just out of curiosity, using for/switch really appears to be around 54% slower than 4 for blocks:

405,520
±0.55%
54% slower

http://jsperf.com/loop-conditions

**Comment by kvz** [comment]
Hey @AyrA, thank you so much for this PR. I am very sorry for the long wait after you put in this work. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). As part of this I'm going over all issues and PRs now. Looking at this one, it seems to me that we can't merge in code that much slower than the original. Closing this for now but feel free to re-open.

**Pull request closed without merging**
