### PR TITLE
Unexpected result when str is null

### PR DESCRIPTION
**Pull request by sirio3mil**
Some lattest browsers when str is null return and unexpected null value

### CODE REVIEW

**Comment by kvz** [comment]
Found one typo: lattest, and also please add a failing test that passes with this addition. Then I'll merge this!

**Comment by sirio3mil** [comment]
I don't know how to add a new test file. How can I do that? I am not familiar with github and TDD.

**Comment by kvz** [comment]
You can add an example and an expected result in the header, automation takes care of the rest ; )

Please also check our coding standards: `if(` should be `if (`

**Comment by kvz** [comment]
And `){` should be `) {`

**Comment by kvz** [comment]
Thanks!

**Pull request merged**
