### PR TITLE
Add php function 'array_walk_recursive'

### PR DESCRIPTION
**Pull request by Tithugues**

### CODE REVIEW

**Comment by kvz** [comment]
Thanks for you time hacking this up, @Tithugues!

A few things that would need to be changed in order for us to be able to merge this in:

- [ ] Passing lint tests, see https://travis-ci.org/kvz/locutus/jobs/135327876#L166 
- [ ] We prefer early returns, see http://debuggable.com/posts/programming-psychology-return-home-early:4811de9f-ae28-49c2-a7dc-2f154834cda3
- [ ] If a `try` block is needed to mimic PHP's behavior, it should be only around the statement that we need to catch and return false for, not around the entire function body

Then it would be nice if this function could accept both js as php-type function callings, but there already is a project-wide todo up on our [CHANGELOG.md](https://github.com/kvz/locutus/blob/master/CHANGELOG.md):

> Investigate if we can have one helper function to resolve Function/'function'/'Class::function'/[$object, 'function'], and use that in is_callable, array_walk, call_user_func_array etc.

So it might be better if the core team discusses and attacks that for all of these functions, after merging this.

**Comment by Tithugues** [comment]
Thanks for your feedback.
I think that 2 first points are OK.
For the last point, can you please tell me if it is now OK?
Thanks.

**Comment by kvz** [comment]
Looking great! As for 3, why do we need the Try? What is going to throw an error that we need to catch? If we can determine the line where that happens, the `try` should just wrap that line, and also return home early, instead of wrapping more code, and it catching more throws than we bargained for. Does this make sense?

If we don't know which statement is throwing an error that we need to catch, then we should remove the try completely for now.

**Comment by Tithugues** [comment]
@kvz I should say that I used src/php/array/array_walk.js as a template for the recursive version.
In this file, the try wraps the if (around the for), so I kept the same structure.
In my opinion, we can't say if the "funcname" function will throw an exception or not. But if it is, the try should at least surround the "funcname" calls. So I moved the try into the for as you suggested.

The only thing I don't know is: does one "try" surrounding one "for" is faster than one "for" surrounding one "try" handled many times?

I just pushed the new version. I let you check if this is better for you.

Thanks for your guidelines.

**Comment by kvz** [comment]
Hi @Tithugues,

There might be a penalty, we could benchmark via e.g. jsperf. But since we're calling a func inside the forloop here, I would argue the the overhead of try is not going to be felt compared to that function call in most cases anyway.

This is good to be merged, thanks for the extra effort!

**Comment by kvz** [comment]
Hey there, I just pushed out [v2.0.5](https://github.com/kvz/locutus/blob/master/CHANGELOG.md#v205) which contains this work.

**Pull request merged**
