### PR TITLE
Better way to test for non-existing function arguments

### PR DESCRIPTION
**Pull request by andreipfeiffer**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description
In JS, checking if an argument is passed to a function call, is usually done by verifying against `undefined`. `null` is a specific value in JS.

### CODE REVIEW

**Comment by kukawski** [comment]
I would like @kvz to have a voice here, because current implementation of this - and many other functions - reflects PHP's behaviour as close as possible.
In PHP a non-existing argument becomes in the end NULL + additional warnings and notices.

**Comment by andreipfeiffer** [comment]
@kukawski sure, no problem.
Also, if you support ES6 features, this could be easily be refactored to use "default arguments", because all that code does is making sure that you have a default value, if none is passed as an argument.

**Comment by kukawski** [comment]
Regarding the `value + ''` -> `String(value)` change. If we want to improve PHP compatibility, then we should use https://github.com/kvz/locutus/blob/master/src/php/_helpers/_phpCastString.js instead, which casts values to string very close to PHP's algorithm.

**Comment by kvz** [comment]
ES6 Is fine and I'd be in favor of using default arguments to settle it. You @kukawski ?

As for doing `String()` vs `+ ''`. Isn't this exactly the same only longer notation? What's the benefit?

**Comment by kukawski** [comment]
@kvz @andreipfeiffer agree, using default params would be an improvement for us.

Regarding `String()` vs `+ ''`, technically both give same results. The only visible benefit would be slightly better code readability (because conversion is explicit).
Don't know about JS engine implementation, but using `String()` would eventually cause just one memory allocation for the converted string, where `+ ''` probably needs at least 2 allocations - one for casting to string and second for concatenating. But that's minor.

Anyway, there is still the topic of using _phpCastString.js for casting in this case.

**Comment by andreipfeiffer** [comment]
Hey @kvz @kukawski in regard to using `_phpCastString.js` I would not recommend this approach.
If you look at the implementation, it performs a lot of checks, so it's definitely slower than any other approach discussed above.

Also, on the case of `Numbers`, all it does is perform a `'' + value`, which you are doing already.

So, just let me know if you need me to prepare another PR, in case you agree upon the explicit `String(value)` proposal.

Thank you guys!

**Comment by andreipfeiffer** [comment]
And in regard to "null checking", I am aware of the "hack" `value == null`.
It's just that this obscures the intent: you don't know if the developer actually wanted to check for `null` values or not. As I can tell from the code, you actually want to set a default value, when certain arguments are not supplied to the function.

If this is the case, then those arguments will always be `undefined`, never `null` (unless you pass the null value explicitly).

If also you want to avoid `null` values being passed, and still make sure that the argument is a number with a default value of 1, then another approach would be:

```
costIns = Number(costIns) || 1
```

This way, if the type coercion results in a NaN (for undefined/null/NaN) it will be initialized with 1.

To keep in mind that ES6 default params are only checked against `undefined`, so they work only when you don't pass the argument, or when you pass explicit `undefined`. When you pass `null`, it will remain `null`.

Just let me know what do you decide or if you want to discuss this in more detail.
I appreciate your interest.

**Comment by Knight-Yoshi** [comment]
Tested in Firefox 57 `(String(n)).replace(/[^0-9+\-Ee.]/g, '')` is 32% slower than `(n+'').replace(/[^0-9+\-Ee.]/g, '');` and Chrome the `String` object is 9% slower. So if we're talking about performance, casting it to a primitive string and performing the replace is faster.

**Comment by andreipfeiffer** [comment]
@Knight-Yoshi I've done some testing myself and I got consistent:
- similar perf in Chrome
- similar perf in Safari
- slightly better perf for `'' + foo` in Firefox

But the fact is that this perf gain/loss is calculated from a very small value, so the actual impact is minimal.
And also, any perf test should be taken with a large dose of skepticism, because it's not trivial to create relevant perf tests.

Most devs prefer the `String(foo)` variant, because it's more explicit.

Apparently, both work similarly behind the scenes:
http://2ality.com/2012/03/converting-to-string.html

But this being a library, I totally get it if you prefer to have a less explicit code base in favor of a maybe a slightly better perf.

**Comment by kvz** [comment]
Sorry for the long delay, while this may or may not be true:

> Most devs prefer the `String(foo)` variant, because it's more explicit.

I personally don't favor the `String` variant, and since it also comes at a performance cost, this is a no go for me. Sorry!

**Comment by KnightYoshi** [comment]
I've seen a lot of JS, but I've never seen anyone use the `String` object explicitly.

https://jsperf.com/string-object-vs-string-primative/1
Tested again using Firefox 63, Chrome 70 on Mac and in Windows using Edge (which was listed as Chrome 64 in the results O.o)

Consistently the primitive type was faster, in Firefox it's still considerably faster. Which makes sense. Since the primitive type isn't calling a object constructor.

**Pull request closed without merging**
