### PR TITLE
#344 fixing issue with delete keyword

### PR DESCRIPTION
**Pull request by oleg-andreyev**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description
Fixing issue #344

### CODE REVIEW

**Comment by kvz** [comment]
Thanks!!

Can we also have a testcase/example that showcases how this would fail before? Just to avoid regressions

**Comment by oleg-andreyev** [comment]
I can't create testcase for this unfortunately, because NodeJS and Chrome does not trigger issue when you're trying to delete undefined property/key from object/array, but PhantomJS does trigger it.

Based on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
> strict mode makes attempts to delete undeletable properties throw (where before the attempt would simply have no effect):

On one hand when you'll try to delete undefined property/key it's okay, on other hand, you can't delete something that does not exists.

I was trying to execute Mocha using Karma Runner, but it was failing because of 'use strict' and access to `argument.callee` from chai framework.

I'll try to prepare standalone page with this case.

**Comment by oleg-andreyev** [comment]
@kvz I've prepare "playground" repo: https://github.com/oleg-andreyev/playground/tree/locutus-344

```
# run current version of array_multisort
npm run run-origin

# run patched version of array_multisort
npm run run-patch
```

**Comment by kvz** [comment]
Thanks!

**Pull request merged**
