### PR TITLE
FIX : Failed tests

### PR DESCRIPTION
**Pull request by argosback**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### CODE REVIEW

**Comment by argosback** [comment]
**pow.js** test fail with Node 12

```
710 passing (529ms)
  23 pending
  1 failing
  1) src/php/math/pow.js (tested in test/languages/php/math/test-pow.js)
       should pass example 1:
      AssertionError: expected 3.843909168077899e+48 to deeply equal 3.8439091680778995e+48
      + expected - actual
      -3.843909168077899e+48
      +3.8439091680778995e+48
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.<computed> [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (test/languages/php/math/test-pow.js:13:28)
      at processImmediate (internal/timers.js:439:21)
```

**Comment by argosback** [comment]
Fixed pow function ;)

**Comment by kvz** [comment]
:heart_decoration:

**Comment by argosback** [comment]
@KnightYoshi you are rigth, my mistake

On **Tests** the **toString()** call print:

```javascript
function MyClass() {
      _classCallCheck(this, MyClass);
    }
```

On **Plain node** the **toString()** call print:

```javascript
class MyClass {}
```
I modified the regular expression test, and now it's working.

**Pull request merged**
