### PR TITLE
Create ascii_letters.js

### PR DESCRIPTION
**Pull request by shapkarin**
Python's ascii_letters

### CODE REVIEW

**Comment by kvz** [comment]
Cool, thanks!

**Comment by shapkarin** [comment]
@kvz can't pass all lint. Just because I can't configure all locally. But I'll try to do that :-)

**Comment by shapkarin** [comment]
@kvz I'll fix errors today. I just removed repository from my account and then forgot that I have open request. Anyway I'll fix all errors today!

**Comment by shapkarin** [comment]
@kvz I found that code didn't pass all checks and create new request to fix that https://github.com/kvz/locutus/pull/382 and sure with additional functions

**Pull request merged**
