### PR TITLE
Fix indent of nested arrays in PHP's var_export

### PR DESCRIPTION
**Pull request by simivar**
Currently for every nested array `var_export` is keeping `array(` string on the same line with indent as key name when in fact it should be in new line.

For example currently `var_export({ test: [ 'a', 'b' ] })` produces:
```
array (
  'test' =>   array (
    0 =&gt; 'a',
    1 =&gt; 'b'
  )
)
```

instead of
```
array (
  'test' =>
  array (
    0 => 'a',
    1 => 'b'
  )
)
```

- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### CODE REVIEW

**Comment by simivar** [comment]
@kvz tests fail because #401

**Comment by kvz** [comment]
Merged that one but this one has a conflict now unfortunately :woman_shrugging:

**Comment by simivar** [comment]
@kvz resolved and it now test are a success :)

**Comment by kvz** [comment]
:heart_decoration:

**Pull request merged**
