### PR TITLE
deserialization support for objects (custom and standard serialization)

### PR DESCRIPTION
**Pull request by hardchor**
I needed a way to deserialize objects in JS. This helped massively: http://www.phpinternalsbook.com/classes_objects/serialization.html

This might also address some of the issues raised around unserialize(), notably #109

### CODE REVIEW

**Comment by steelbrain** [comment]
Bump.

**Comment by hardchor** [comment]
@kvz This has been hanging around for 2 years. Come on!

**Comment by steelbrain** [comment]
I ended up creating https://github.com/steelbrain/php-serialize

**Comment by kvz** [comment]
Although I don't think this is the way to encourage open source developers to do more work for you, I do think you're raising a good point. I am unfit to maintain this project. I have been asking for someone to take over this project for a long time, but it seems there is no one leader who wants to do this. Yet, the community around this project is still very much breathing. This leads me to think the project should be under an independent organization, where it can be governed by the community. The most prolific devs will have admin access. I'll write a blogpost on this soon.

**Comment by kvz** [comment]
Hey @hardchor, thank you so much for this PR. I am very sorry for the long wait after you put in this work. This project and my motivation were in a bad spot. I thought about this for a long time and decided to redo the project. I recently breathed new life into it (http://locutus.io/2016/05/announcing-locutus/). Unfortunately for your PR this also means it's currently outdated and cannot be merged as is.

I'll close this issues, but if this PR is still relevant to you, please re-open. You should then rebase with this project's `master` branch, make sure it complies with the contributing document (https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md), and then we can merge this in, because the work really does look good to me.

Again, I'm very sorry for not having giving this the attention it deserves earlier, and putting you through all this extra hassle. That's all on me and being overrun by this project. I hope you'll agree though that the project was in a dead-end street, and with this new big push, we're going somewhere again.

**Pull request closed without merging**
