### PR TITLE
Create array_column.js

### PR DESCRIPTION
**Pull request by Enzarro**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description
PHP's array_function. It works pretty well, it's very simple, I have used it in many projects and I'm pretty sure it can be improved by more talented people.

### CODE REVIEW

**Comment by argosback** [comment]
Hi @Enzarro some fixes to your code

- (`{`{...},{...}`}`, 'name'}) → (`[`{...},{...}`]`, 'name'})
- {name: '**Michel**', value: 3} → {name: '**Michael**', value: 3}


```javascript
module.exports = function array_column (array, columnName) { // eslint-disable-line camelcase
  //  discuss at: http://locutus.io/php/array_column/
  // original by: Enzo Dañobeytía
  //   example 1: array_column([{name: 'Alex', value: 1}, {name: 'Elvis', value: 2}, {name: 'Michael', value: 3}], 'name')
  //   returns 1: ['Alex', 'Elvis', 'Michael']

  if (array !== null) {
    if (Array.isArray(array)) {
      return array.map(function (value, index) {
        return value[columnName]
      })
    } else if (typeof array === 'object') {
      var newarray = []
      for (var key in array) {
        newarray.push(array[key][columnName]);
      }
      return newarray
    }
  }
}

```

**Comment by argosback** [comment]
Third parameter is missing

**array_column**
_(PHP 5 >= 5.5.0, PHP 7)_

array_column — Return the values from a single column in the input array

```php
array_column ( array $input , mixed $column_key [, mixed $index_key = NULL ] ) : array
```

### index_key

> The column to use as the index/keys for the returned array. This value may be the integer key of the column, or it may be the string key name. The value is cast as usual for array keys (however, objects supporting conversion to string are also allowed).

**Comment by Enzarro** [comment]
> Third parameter is missing
> 
> **array_column**
> _(PHP 5 >= 5.5.0, PHP 7)_
> 
> array_column — Return the values from a single column in the input array
> 
> ```
> array_column ( array $input , mixed $column_key [, mixed $index_key = NULL ] ) : array
> ```
> 
> ### index_key
> > The column to use as the index/keys for the returned array. This value may be the integer key of the column, or it may be the string key name. The value is cast as usual for array keys (however, objects supporting conversion to string are also allowed).

Thanks, I added third parameter.

**Comment by argosback** [comment]
Hello @Enzarro making these changes the tests pass.

```patch
9c9
<     //   returns 3: [empty, 1: 'Alex', 2: 'Elvis', 3: 'Michael']
---
>     //   returns 3: [, 'Alex', 'Elvis', 'Michael']
11c11
<     //   returns 4: [empty, 1: {name: 'Alex', value: 1}, 2: {name: 'Elvis', value: 2}, 3: {name: 'Michael', value: 3}]
---
>     //   returns 4: [, {name: 'Alex', value: 1}, {name: 'Elvis', value: 2}, {name: 'Michael', value: 3}]
```

**Comment by argosback** [comment]
I have tried with the examples that come in the official documentation of PHP and the function does not return the values ​​that are expected.

**Your script**


**PHP**


> References:
 - [array_column](https://www.php.net/manual/en/function.array-column.php)

**Pull request merged**
