### PR TITLE
Upgrade to Jest

### PR DESCRIPTION
**Pull request by cpojer**
Live from jsconf! HI! I'll explain later.

### CODE REVIEW

**Comment by kvz** [comment]
We auto-generate the tests 😄 But I assume you also used automation for this, and I'm happy to learn about it as I have a few other projects still on mocha that i'd love to port to jest as well 💯 🎖

**Comment by kvz** [comment]
Good luck with your talk 👊  and say hi to the folks at jsconf 👋

**Comment by cpojer** [comment]
Yes, that is true but it was a good way during the conference to send out an automated codemod on a large amount of files :) Jest actually makes the test-suite here a little bit faster (on subsequent runs), so if you are interested in adopting it, it should be easy. After the codemod/regenerating the tests, only about 8 or so fail. The talk went great, I sent this pull request during it.

**Comment by skovhus** [comment]
@kvz let me know if need any help migrating to Jest. @cpojer used https://github.com/skovhus/jest-codemods to migrate the tests over. : )

**Comment by kvz** [comment]
Well so the tests are generated by looking at the function's header comments. So we'd need to modify the generator and not its results.

I'm open to switching to Jest, but don't have the time to hammer that out at the moment

**Pull request closed without merging**
