### PR TITLE
Convert Non-strict to strict equality checking

### PR DESCRIPTION
**Pull request by kale-io**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description
Strict equality checks are desired in JS, so you don't rely on implicit type coercion.
In these particular scenarios, `RegExp.exec` will return `null` if the match fails.
And `String.length` will always return a `Number`, so the logic won't be affected.

### CODE REVIEW

**Comment by kvz** [comment]
Thanks for the work here. Agreed in general! Do watch out for `== null` though. In linters this is often explicitly allowed to match for both null && undefined. Making those `=== null` might cause different/invalid behavior.

Also not sure about `String()` vs `+ ''`. Isn't this exactly the same only longer notation?

Let me know your thoughts, and also when this is no longer a work in progress so we can give the final nay/okay.

**Comment by kukawski** [comment]
I also agree, that we need to be careful when modifying `== null` comparison to strict. Especially if we care about being compatible with PHP as close as possible. In PHP ommiting a param makes it basically have a NULL value. `== null` comparison allows to catch both, null and undefined values, which is perfect for our use case.

@kvz topic `String()` vs `+ ''` should be mentioned here https://github.com/kvz/locutus/pull/353 ;-)

**Comment by kvz** [comment]
Ah oops, will fix :)

**Comment by kvz** [comment]
Closing this as there are only `null` comparisons and they are not candidates for triple equality

**Pull request closed without merging**
