### PR TITLE
Reduce the codebase

### PR DESCRIPTION
**Pull request by CodeKraft**
Simplify the code base so that the function is smaller and change the "if" conditional logic to test for strict state and if theirs a result or not.

### CODE REVIEW

**Comment by kvz** [comment]
While the function isn't 100% adhering our coding standards as it is, putting inlining ifs doesn't improve that.

Thanks for your time but we can't accept this one.

**Comment by CodeKraft** [comment]
Sorry but the code is just as valid as any other coding method and inlining is a valid method of streamlining code, making it more user readable and your code base is 5 lines~ish and not 20 lines.

So, where do I find a copy of your coding standards if you don't mind dropping me a URL, I will take a look.

**Comment by kvz** [comment]
You can go to http://phpjs.org/

I know the code is functioning but since we're working with 1800 people on this codebase we're aiming for a consistent look.

I'm also missing testcases that address the issue you were fixing by the way.
Just reducing linenumbers is not by definition considered a win in our project.

**Comment by kvz** [comment]
Hey @CodeKraft, thank you so much for this PR. I am very sorry for the long wait after you put in this work. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). As part of this I'm going over all issues and PRs now. Looking at this one, it seems to me that it does not match our coding standards. They were changed to JavaScript standard, but that does not affect this PR. Closing this for now but feel free to re-open.

**Pull request closed without merging**
