### PR TITLE
isset returns false on blank strings

### PR DESCRIPTION
**Pull request by ftrotter**
so now it is more compatible with php

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### CODE REVIEW

**Comment by kvz** [comment]
Correct me if I'm wrong but i don't think in PHP this equals false?

```
$ php -e
<?php
$var = '';
echo isset($var);
1
```

**Comment by kukawski** [comment]
In PHP calling `isset('string literal')` throws a `Fatal Error: Cannot use isset() on the result of an expression`.
On a variable who's value is empty string, it returns `true`, because the var is set.
This PR seems to be invalid.

**Comment by willrowe** [comment]
A variable set to an empty string is considered set as can be seen here: [https://3v4l.org/Wv8es](https://3v4l.org/Wv8es).

**Comment by ftrotter** [comment]
Sorry about this, not sure how I made that mistake... 

-FT

**Comment by ftrotter** [comment]
I think I was reading the documentation empty() sorry for the mixup.

**Comment by kvz** [comment]
No worries! I’ve definitely committed to much bigger mistakes :)

**Pull request closed without merging**
